version: "3"
services:
  backend:
    container_name: backend 
    build:
        context: ./backend
    entrypoint: ["npm", "run", "start:prod"]
    depends_on:
      - db  
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    environment:  
      - MONGO_URL=monogdb://db:27017/monodrippy
      - APP_PORT=80
    ports: ['3001:3001']
    command: npm run start:prod 

  db:
    container_name: db
    image: mongo:4.0
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    environment:  
      - BACKEND_URL=http://localhost/monodrippy